local config = {
    [0] = {
        no_skill=-2,
        icon=1,
        ID=0,
        offsetGroup=1,
        name="绿毒",
        tips="每秒受到一定的伤害",
    },
    [1] = {
        no_skill=-2,
        icon=1,
        ID=1,
        offsetGroup=1,
        name="红毒",
        tips="降低一定防御能力",
    },
    [5] = {
        no_skill=-1,
        dis_action=7,
        icon=5,
        ID=5,
        offsetGroup=1,
        bufftitle="你被麻痹了",
        name="麻痹",
        tips="无法移动，无法攻击",
    },
    [6] = {
        no_skill=-2,
        icon=11,
        ID=6,
        offsetGroup=1,
        name="无极真气",
        tips="大幅度提高自身伤害",
    },
    [7] = {
        no_skill=-2,
        icon=11,
        ID=7,
        offsetGroup=1,
        name="护体神盾",
        tips="提高格挡概率和格挡伤害",
    },
    [8] = {
        no_skill=-2,
        icon=8,
        ID=8,
        offsetGroup=1,
        name="隐身",
        tips="不会被怪物发现，移动破除隐身状态",
    },
    [9] = {
        no_skill=-2,
        icon=15,
        ID=9,
        offsetGroup=1,
        name="神圣战甲术",
        tips="提高防御能力",
    },
    [10] = {
        no_skill=-2,
        icon=14,
        ID=10,
        offsetGroup=1,
        name="幽灵盾",
        tips="提高魔防能力",
    },
    [11] = {
        no_skill=-2,
        front_sfx_stuck="50#50",
        icon=11,
        ID=11,
        offsetGroup=1,
        tips="降低受到的伤害",
        name="魔法盾",
        front_sfx="49#49",
    },
    [12] = {
        no_skill=-2,
        front_sfx_stuck="150#150",
        icon=11,
        ID=12,
        offsetGroup=1,
        tips="降低受到的伤害",
        name="强化魔法盾",
        front_sfx="149#149",
    },
    [13] = {
        dis_action=2,
        icon=1113,
        overlap=0,
        offsetGroup=1,
        Priority=1,
        front_sfx="2950#2950",
        no_skill=-2,
        uniqueType=25,
        replaceGroup=0,
        ID=13,
        group=0,
        time="2#3000",
        name="禁锢",
        tips="无法进行跑步操作",
    },
    [14] = {
        no_skill=-2,
        front_sfx_stuck="2951#2951",
        replaceGroup=1,
        ID=14,
        dis_action=2,
        name="蛛网",
        front_sfx="2951#2951",
    },
    [21] = {
        no_skill=-1,
        front_sfx_stuck="145#145",
        offsetGroup=1,
        ID=21,
        tips="雷霆剑法BUFF，目标变色",
        name="雷霆剑法_BUFF",
        front_sfx="145#145",
    },
    [22] = {
        dis_action=11,
        offsetGroup=1,
        ID=22,
        color=9,
        name="战士连击技能锁定",
        tips="战技封锁，不能移动，不能施法",
    },
    [23] = {
        front_sfx_stuck="432#432",
        offsetGroup=1,
        ID=23,
        tips="万剑归宗的BUFF特效",
        name="道士连击万剑归宗",
        front_sfx="432#432",
    },
    [69] = {
        no_skill=-1,
        offsetGroup=1,
        ID=69,
        dis_action=31,
        name="锁定",
        tips="无法移动，无法攻击",
    },
    [71] = {
        no_skill=-1,
        offsetGroup=1,
        ID=71,
        name="禁止攻击",
        tips="无法释放攻击",
    },
    [77] = {
        no_skill=-2,
        front_sfx_stuck="442#442",
        offsetGroup=1,
        ID=77,
        tips="时间生效内-无视一切麻痹",
        name="唯我独尊_自身触发",
        front_sfx="442#442",
    },
    [78] = {
        no_skill=-2,
        offsetGroup=1,
        ID=78,
        color=13,
        name="唯我独尊_他人触发",
        tips="周围其他人降低防御",
    },
    [80] = {
        front_sfx_stuck="518#518",
        ID=80,
        tips="潜行特效",
        name="潜行术",
        front_sfx="518#518",
    },
    [1113] = {
        no_skill=-1,
        icon=5,
        ID=1113,
        offsetGroup=1,
        dis_action=7,
        name="冰冻",
        tips="无法移动，无法攻击",
    },
    [2008] = {
        dis_action=-1,
        icon=5,
        overlap=0,
        offsetGroup=1,
        no_item=527,
        behind_sfx="5005#5005",
        Priority=1,
        ID=2008,
        group=0,
        time="2#7200",
        name="摆摊BUFF",
        tips="摆摊BUFF",
    },
}
return config
